server:
  port: 80
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/rainbow-api-user

  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: non_null
      time-zone: GMT+8